# Generated by Django 5.0.3 on 2024-03-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_remove_veiculo_acessorio_veiculo_acessorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='acessorio',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(related_name='veiculos', to='garagem.acessorio'),
        ),
    ]
